In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [2]:
x=np.array([[200.0,17.0]])

layer_1 = keras.layers.Dense(units=3, activation="sigmoid") #this layer has 3 neurons and uses sigmoid activation function
a1 = layer_1(x)

In [ ]:
layer_2 = keras.layers.Dense(units=1, activation="sigmoid") #this layer has 1 neuron and uses sigmoid activation function
a2 = layer_2(a1) # pass output of previous layer as input to the next layer

In [4]:
print(a1)
print(a2)

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.6219797]], shape=(1, 1), dtype=float32)


In [5]:
a1.numpy()

array([[1., 0., 0.]], dtype=float32)

In [14]:
# layer using sequential

model = keras.Sequential([layer_1,layer_2])

In [ ]:
model.predict(np.array([[200.0,17.0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


array([[0.3630258]], dtype=float32)

In [24]:
model.compile()
model.fit(x=np.array([[200.0,17.0]]),y = np.array([[1.0]]),epochs=5)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 945ms/step - accuracy: 1.0000 - loss: 0.4531
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 1.0000 - loss: 0.4508
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.4491
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 1.0000 - loss: 0.4477
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.4465


In [42]:
x = np.array([[200.0,17.0],[120.0,5.0],[425.0,20.0],[212.0,18.0]])
y = np.array([1,0,0,1])

In [43]:
model_new = keras.Sequential([
    keras.layers.Dense(units=3, activation="sigmoid"),
    keras.layers.Dense(units=1, activation="sigmoid")
])

In [45]:
model_new.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_new.fit(x, y, epochs=5)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.9048
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 0.9039
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.9030
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - loss: 0.9021
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.9013


In [51]:
model_new.predict(np.array([[101.0,9.0]]))
# x

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step


array([[0.79124844]], dtype=float32)