In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [ ]:
x=np.array([[200.0,17.0]])

layer_1 = keras.layers.Dense(units=3, activation="sigmoid") #this layer has 3 neurons and uses sigmoid activation function
a1 = layer_1(x)

In [9]:
layer_2 = keras.layers.Dense(units=1, activation="sigmoid") #this layer has 1 neuron and uses sigmoid activation function
a2 = layer_2(a1) # pass output of previous layer as input to the next layer

In [11]:
print(a1)
print(a2)

tf.Tensor([[1.         0.06657381 1.        ]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.735157]], shape=(1, 1), dtype=float32)


In [12]:
a1.numpy()

array([[1.        , 0.06657381, 1.        ]], dtype=float32)